global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

# Outputs:
#
# Grafana_URL = "http://54.175.232.165:3000"
# Prometheus_URL = "http://54.175.232.165:9090"