---
- name: Add Prometheus user
  user:
    name: prometheus
    state: present
    create_home: no

- name: Download Prometheus and Unarchive
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus yml to /etc/prometheus
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/

- name: Copy prometheus service to systemd folder
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: Install Prometheus
  become: true
  shell: |
    cd /tmp

    mkdir /var/lib/prometheus

    cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
    cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
    cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus

    rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64

    chown prometheus:prometheus /etc/prometheus
    chown prometheus:prometheus /usr/local/bin/prometheus
    chown prometheus:prometheus /usr/local/bin/promtool
    chown -R prometheus:prometheus /etc/prometheus/consoles
    chown -R prometheus:prometheus /etc/prometheus/console_libraries
    chown -R prometheus:prometheus /var/lib/prometheus

    systemctl daemon-reload
    systemctl enable prometheus
    systemctl start prometheus

    exit 0
  args:
    executable: /bin/bash

