---
- name: Add Node Exporter user
  user:
    name: node_exporter
    state: present
    create_home: no

- name: Download Node Exporter and Unarchive
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    dest: /tmp/
    remote_src: yes

- name: Copy prometheus yml to /etc/prometheus
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/

- name: Copy node exporter service to systemd folder
  become: true
  copy:
    src: node-exporter.service
    dest: /etc/systemd/system/

- name: Install Node Exporter
  become: true
  shell: |
    cd /tmp

    cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    # systemctl status node-exporter

    exit 0
  args:
    executable: /bin/bash

